version: 1.{build}
branches:
  only:
  - master
skip_tags: true
environment:
  PYTHON_PATH: C:\Python35
  GH_TOKEN:
    secure: cBLet7SS/ylM4b8BMnKq5waFa0KB4sn+gKz9MMCcKdUQ2t8g3zrKPErkOGF7vQmQ
install:
- cmd: >-
    set PATH=C:\Program Files\Git\usr\bin;%PYTHON_PATH%;%PATH%

    %PYTHON_PATH%\python --version

    %PYTHON_PATH%\Scripts\pip install -r requirements.txt
build_script:
- cmd: bash "build.sh"
test: off
