version: 1.{build}
branches:
  only:
  - master
skip_tags: true
environment:
  PYTHON_PATH: C:\Python35
  GH_TOKEN:
    secure: UCQIa6hxhDMnG2fr/+gVbyZZQCFN0a5+aVwmUsIGUA6vWvAYIY8NVCcc0kRxhR5x
install:
- cmd: >-
    set PATH=C:\Program Files\Git\usr\bin;%PYTHON_PATH%;%PATH%

    %PYTHON_PATH%\python --version

    %PYTHON_PATH%\Scripts\pip install -r requirements.txt
build_script:
- cmd: bash "build.sh"
test: off
